---

workflow_soe_content_delivery_pipeline_dev:
  name: "SOE_ContentDeliveryPipeline"
  description: "SOE content delivery pipeline for the Development Lifecycle"
  organization: "Default"
  state: present
  workflow_nodes:
    - identifier: "Define"
      unified_job_template:
        name: "Dev1PublishContent"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Deliver"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Deliver"
      unified_job_template:
        name: "Dev2PromoteToDev"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Deploy"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Deploy"
      unified_job_template:
        name: "Dev3DeployTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Snapshot"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Snapshot"
      unified_job_template:
        name: "Dev4SnapshotTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "ConfigureApp1"
          - identifier: "ConfigureApp2"
          - identifier: "ConfigureApp3"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "ConfigureApp1"
      unified_job_template:
        name: "Dev5.1.1BuildJBoss"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "TestApp1"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "TestApp1"
      unified_job_template:
        name: "Dev5.1.2TestJBoss"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNext"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "ConfigureApp2"
      unified_job_template:
        name: "Dev5.2.1BuildLAMP"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "TestApp2"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "TestApp2"
      unified_job_template:
        name: "Dev5.2.2TestLAMP"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNext"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "ConfigureApp3"
      unified_job_template:
        name: "Dev5.3.1BuildWordpress"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "TestApp3"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "TestApp3"
      unified_job_template:
        name: "Dev5.3.2TestWordpress"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNext"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "PromoteNext"
      all_parents_must_converge: true
      unified_job_template:
        name: "Dev6PromoteToQA"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "DeleteSnapshot"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "DeleteSnapshot"
      unified_job_template:
        name: "Dev7DeleteSnapshots"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "ApproveDeleteHosts"
        failure_nodes:
          - identifier: "PowerOffHosts"
        always_nodes: []
        credentials: []
    - identifier: "ApproveDeleteHosts"
      unified_job_template:
        name: "ApproveDeleteHosts"
        timeout: 10800
        type: workflow_approval
        description: "Approved to delete test hosts?"
      related:
        success_nodes:
          - identifier: "DeleteHosts"
        failure_nodes:
          - identifier: "PowerOffHosts"
        always_nodes: []
        credentials: []
    - identifier: "DeleteHosts"
      unified_job_template:
        name: "Dev8SDeleteTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "PowerOffHosts"
      organization: "Default"
      unified_job_template:
        name: "Dev8FPowerOffTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
