---

static_hosts:
  - name: "sat6.parmstrong.ca"
    description: "The satellite server"
    enabled: true
    inventory: "TheSatellite"
    state: present

  - name: "aapcontroller24.parmstrong.ca"
    description: "The AAP Controller server"
    enabled: true
    inventory: "TheAutomationController"
    state: present

  - name: "testjboss2.parmstrong.ca"
    description: "jboss SOE test host"
    enabled: true
    inventory: "SOE_pipeline_inventory"
    state: present
    variables:
      fqdn: "testjboss2.parmstrong.ca"
      hostgroup: "hg_x86_64_rhel8_vm/dev/soe_jboss"
      kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
      compute_resource: "vcenter.parmstrong.ca"
      compute_profile: "SOE_Medium"
      mac: "00:50:56:ff:ff:ff"
      dhostname: ""

  - name: "testlamp2.parmstrong.ca"
    description: "LAMP stack SOE test host"
    enabled: true
    inventory: "SOE_pipeline_inventory"
    state: present
    variables:
      fqdn: "testlamp2.parmstrong.ca"
      hostgroup: "hg_x86_64_rhel8_vm/dev/soe_lamp"
      kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
      compute_resource: "vcenter.parmstrong.ca"
      compute_profile: "SOE_Medium"
      mac: "00:50:56:ff:ff:ff"
      dhostname: ""

  - name: "testwordpress2.parmstrong.ca"
    description: "Wordpress SOE test host"
    enabled: true
    inventory: "SOE_pipeline_inventory"
    state: present
    variables:
      fqdn: "testwordpress2.parmstrong.ca"
      hostgroup: "hg_x86_64_rhel8_vm/dev/soe_wordpress"
      kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
      compute_resource: "vcenter.parmstrong.ca"
      compute_profile: "SOE_Medium"
      mac: "00:50:56:ff:ff:ff"
      dhostname: ""

  - name: "centosdemo1.parmstrong.ca"
    description: "convert2rhel test host"
    enabled: true
    inventory: "convert2rhel_pipeline_inventory"
    state: present
    variables:
      fqdn: "centosdemo1.parmstrong.ca"
      delete_host: false
      organization: "Default Organization"
      location: "Default Location"
      hostgroup: "hg_x86_64_centos79_vm"
      compute_resource: "vcenter.parmstrong.ca"
      compute_profile: "2-Medium"
      mac: "00:50:56:ff:ff:ff"
      comment: "c2r_demo_host deleteme"

  - name: "centosdemo2.parmstrong.ca"
    description: "convert2rhel test host"
    enabled: true
    inventory: "convert2rhel_pipeline_inventory"
    state: present
    variables:
      fqdn: "centosdemo2.parmstrong.ca"
      delete_host: false
      organization: "Default Organization"
      location: "Default Location"
      hostgroup: "hg_x86_64_centos79_vm"
      compute_resource: "vcenter.parmstrong.ca"
      compute_profile: "2-Medium"
      mac: "00:50:56:ff:ff:ff"
      comment: "c2r_demo_host deleteme"

  - name: "oeldemo1.parmstrong.ca"
    description: "convert2rhel test host"
    enabled: true
    inventory: "convert2rhel_pipeline_inventory"
    state: present
    variables:
      fqdn: "oeldemo1.parmstrong.ca"
      delete_host: false
      organization: "Default Organization"
      location: "Default Location"
      hostgroup: "hg_x86_64_oel79_vm"
      compute_resource: "vcenter.parmstrong.ca"
      compute_profile: "2-Medium"
      mac: "00:50:56:ff:ff:ff"
      comment: "c2r_demo_host deleteme"

  - name: "oeldemo2.parmstrong.ca"
    description: "convert2rhel test host"
    enabled: true
    inventory: "convert2rhel_pipeline_inventory"
    state: present
    variables:
      fqdn: "oeldemo2.parmstrong.ca"
      delete_host: false
      organization: "Default Organization"
      location: "Default Location"
      hostgroup: "hg_x86_64_oel79_vm"
      compute_resource: "vcenter.parmstrong.ca"
      compute_profile: "2-Medium"
      mac: "00:50:56:ff:ff:ff"
      comment: "c2r_demo_host deleteme"
