---

workflow_c2r_pipeline:
  name: "c2r_pipeline"
  description: "Automate convert2rhel pipeline for OEL and CentOS applications"
  organization: "Default"
  state: present
  workflow_nodes:
    - identifier: "Prerequisites"
      unified_job_template:
        name: "c2r_prereq_sat"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Pre Convert Remediate"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Pre Convert Remediate"
      unified_job_template:
        name: "c2r_preconvert_remediate"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Analyze"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Analyze"
      unified_job_template:
        name: "c2r_analyze"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Prepare Snapshot Devices"
        failure_nodes: []
        always_nodes:
          - identifier: "Export Report"
        credentials: []
    - identifier: "Prepare Snapshot Devices"
      unified_job_template:
        name: "c2r_snapshot_prepare"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Create Snapshot"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Export Report"
      unified_job_template:
        name: "c2r_report_export"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Create Snapshot"
      unified_job_template:
        name: "c2r_snapshot_create"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Convert"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Convert"
      unified_job_template:
        name: "c2r_convert"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Post Convert Remediate"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Post Convert Remediate"
      unified_job_template:
        name: "c2r_post_remediate"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Post Convert Validate"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Post Convert Validate"
      unified_job_template:
        name: "c2r_post_validate"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Approve Commit"
        failure_nodes:
          - identifier: "Approve Revert"
        always_nodes: []
        credentials: []
    - identifier: "Approve Commit"
      unified_job_template:
        name: "c2r_approve_commit"
        timeout: 10800
        type: workflow_approval
        description: "Approve commit of converted hosts?"
      related:
        success_nodes:
          - identifier: "Commit System"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Commit System"
      unified_job_template:
        name: "c2r_snapshot_remove"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Snapshot Cleanup"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Snapshot Cleanup"
      organization: "Default"
      unified_job_template:
        name: "c2r_snapshot_cleanup"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Approve Revert"
      unified_job_template:
        name: "c2r_approve_revert"
        timeout: 10800
        type: workflow_approval
        description: "Approve revert to orginal state for failed conversions?"
      related:
        success_nodes:
          - identifier: "Revert System"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Revert System"
      organization: "Default"
      unified_job_template:
        name: "c2r_snapshot_revert"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
