---
# this controls our build in Satellite

satellite_fqdn: "sat6.parmstrong.ca"
satellite_admin_username: "{{ satellite_admin_username_vault }}"
satellite_admin_password: "{{ satellite_admin_password_vault }}"
satellite_initial_location: "Default Location"
satellite_initial_organization: "Default Organization"
satellite_location: "{{ satellite_initial_location }}"
satellite_organization: "{{ satellite_initial_organization }}"
satellite_domain: "parmstrong.ca"
satellite_server_url: "https://{{ satellite_fqdn }}"
satellite_validate_certs: true

search_dh_mac: "ff:ff:ff:ff:ff:ff"
# default_vm_mac: "00:50:56:ff:ff:ff"

post_deploy_timeout: 600  # seconds
use_sync_build: false
discovered_hosts_resource: "discovered_hosts"

# platform_hosts:
  # - fqdn: "aapcontroller1.parmstrong.ca"
  #   delete_host: false
  #   organization: "Default Organization"
  #   location: "Default Location"
  #   hostgroup: "hg_x86_64_rhel9_metal"
  #   kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
  #   compute_resource: "baremetal"
  #   mac: "94:c6:91:a3:1b:79"
  # - fqdn: "aapedacontroller.parmstrong.ca"
  #   delete_host: false
  #   organization: "Default Organization"
  #   location: "Default Location"
  #   hostgroup: "hg_x86_64_rhel9_metal"
  #   kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
  #   compute_resource: "baremetal"
  #   mac: "94:c6:91:a3:1d:fb"
  # - fqdn: "aapdb.parmstrong.ca"
  #   delete_host: false
  #   organization: "Default Organization"
  #   location: "Default Location"
  #   hostgroup: "hg_x86_64_rhel9_metal"
  #   kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
  #   compute_resource: "baremetal"
  #   mac: "94:c6:91:a3:1d:ed"
  # - fqdn: "aapgateway1.parmstrong.ca"
  #   delete_host: false
  #   organization: "Default Organization"
  #   location: "Default Location"
  #   hostgroup: "hg_x86_64_rhel9_metal"
  #   kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
  #   compute_resource: "baremetal"
  #   mac: "94:c6:91:a3:1d:50"
  # - fqdn: "aaphub1.parmstrong.ca"
  #   delete_host: false
  #   organization: "Default Organization"
  #   location: "Default Location"
  #   hostgroup: "hg_x86_64_rhel9_metal"
  #   kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
  #   compute_resource: "baremetal"
  #   mac: "94:c6:91:a3:19:6b"

# platform_hosts:
#   - fqdn: "maurice1.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_metal"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "baremetal"
#     mac: "94:c6:91:a2:cd:d4"
#   - fqdn: "maurice2.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_metal"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "baremetal"
#     mac: "94:c6:91:a2:76:74"


# discovered_hosts_resource: "discovered_hosts"
# discovered_hosts_search: "disk_count = 1 and memory > 32000"
# discovered_host_req_nic_count: 1  # we use > below so does not include lo
# default_vm_mac: "00:50:56:ff:ff:ff"
# platform_hosts:
#   - fqdn: "ssc-spc-demo1.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_metal"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "baremetal"
#     mac: "94:c6:91:a3:19:6b"
#   - fqdn: "ssc-spc-demo2.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_vm"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "vcenter.parmstrong.ca"
#     mac: "{{ default_vm_mac }}"
#   - fqdn: "ssc-spc-demo3.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel9_metal"
#     kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
#     compute_resource: "baremetal"
#     mac: "94:c6:91:a3:17:1e"
#   - fqdn: "ssc-spc-demo4.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel8_vm/dev/soe_jboss/CIS2"
#     kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
#     compute_resource: "vcenter.parmstrong.ca"
#     mac: "{{ default_vm_mac }}"
#   - fqdn: "ssc-spc-demo5.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Default Location"
#     hostgroup: "hg_x86_64_rhel8_metal/CIS2Encrypted"
#     kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
#     compute_resource: "baremetal"
#     mac: "94:c6:91:a3:18:02"
#   - fqdn: "ssc-spc-demo6.parmstrong.ca"
#     delete_host: false
#     organization: "Default Organization"
#     location: "Azure"
#     hostgroup: "hg_x86_64_rhel8_azure"
#     kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
#     compute_resource: "AzureCC"
#     mac: "{{ default_vm_mac }}"

# Ansible 2.4 single-node deployment
platform_hosts:
  - fqdn: "aapcontroller24.parmstrong.ca"
    delete_host: false
    organization: "Default Organization"
    location: "Default Location"
    hostgroup: "hg_x86_64_rhel9_metal"
    kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
    compute_resource: "baremetal"
    mac: "94:c6:91:a3:17:3d"
