---

workflow_soe_content_delivery_pipeline:
  name: "SOE_ContentDeliveryPipeline"
  description: "SOE content delivery pipeline for the Development Lifecycle"
  organization: "Default"
  state: present
  workflow_nodes:
    - identifier: "Define"
      unified_job_template:
        name: "ACM1PublishContent"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Deliver"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Deliver"
      unified_job_template:
        name: "ACM2PromoteToDev"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Deploy"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Deploy"
      unified_job_template:
        name: "ACM3DeployTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Snapshot"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Snapshot"
      unified_job_template:
        name: "ACM4SnapshotTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Configure1"
          - identifier: "Configure2"
          - identifier: "Configure3"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Configure1"
      unified_job_template:
        name: "ACM5.1.1BuildJBoss"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Test1"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Test1"
      unified_job_template:
        name: "ACM5.1.2TestJBoss"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNext"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Configure2"
      unified_job_template:
        name: "ACM5.2.1BuildLAMP"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Test2"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Test2"
      unified_job_template:
        name: "ACM5.2.2TestLAMP"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNext"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Configure3"
      unified_job_template:
        name: "ACM5.3.1BuildWordpress"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "Test3"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "Test3"
      unified_job_template:
        name: "ACM5.3.2TestWordpress"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNext"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "PromoteNext"
      all_parents_must_converge: true
      unified_job_template:
        name: "ACM6PromoteToQA"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "DeleteSnapshot"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "DeleteSnapshot"
      unified_job_template:
        name: "ACM7DeleteSnapshots"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "ApproveDeleteHosts"
        failure_nodes:
          - identifier: "PowerOffHosts"
        always_nodes: []
        credentials: []
    - identifier: "ApproveDeleteHosts"
      unified_job_template:
        name: "ApproveDeleteHosts"
        timeout: 10800
        type: workflow_approval
        description: "Approved to delete test hosts?"
      related:
        success_nodes:
          - identifier: "DeleteHosts"
        failure_nodes:
          - identifier: "PowerOffHosts"
        always_nodes: []
        credentials: []
    - identifier: "DeleteHosts"
      unified_job_template:
        name: "ACM8SDeleteTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "PowerOffHosts"
      organization: "Default"
      unified_job_template:
        name: "ACM8FPowerOffTestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
