---
# we are building all hosts with satellite compute resources
- name: "Configure the ansible environment"
  hosts: provisioner
  become: true
  gather_facts: true

  tasks:

    - name: "Update collections"
      ansible.builtin.command: "ansible-galaxy collection install -r {{ playbook_dir }}/requirements.yml"
      register: result
      changed_when: result.rc == 0
      tags:
        - tags_init

- name: "Create hosts"
  hosts: provisioner
  become: true

  tasks:
    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Load the vault variables"
      when: vault_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vault_dir }}"

    - name: "Load the other variables"
      when: vars_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vars_dir }}"

    - name: "Build the ansible platform nodes"
      ansible.builtin.include_role:
        name: platform_node_build
      tags:
        - tags_phase_4
        - tags_platform
        - tags_platform_provisioner


- name: "Apply installation prequisites to hosts"
  hosts: 'all:!provisioner'
  become: true

  tasks:
    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Load the vault variables"
      when: vault_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vault_dir }}"

    - name: "Load the other variables"
      when: vars_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vars_dir }}"

    - name: "Set up the prerequesites for the nodes"
      ansible.builtin.include_role:
        name: platform_node_pre
      tags:
        - tags_phase_4
        - tags_platform
        - tags_all_nodes

- name: "Install the Ansible Automation Platform"
  hosts: "platform_installer"
  become: true

  tasks:
    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Load the vault variables"
      when: vault_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vault_dir }}"

    - name: "Load the other variables"
      when: vars_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vars_dir }}"

    - name: "Download and run the platform installer"
      ansible.builtin.include_role:
        name: platform
      tags:
        - tags_phase_4
        - tags_platform
        - tags_platform_installer

- name: "Configure the Ansible Automation Platform Controller"
  hosts: "platform_installer"
  become: true

  tasks:
    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

    - name: "Load the vault variables"
      when: vault_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vault_dir }}"

    - name: "Load the other variables"
      when: vars_dir is defined
      ansible.builtin.include_vars:
        dir: "{{ vars_dir }}"

    - name: "Add all AAP Content and Configuration"
      when: groups['aap_controllers'] | length > 0
      ansible.builtin.include_role:
        name: platform_post
      tags:
        - tags_phase_4
        - tags_platform
        - tags_platform_post
