---
# These are the collections required by the builder
# We no longer support AAP versions prior to AAP 2.5

collections:
  - name: "ansible.controller"
  - name: "ansible.netcommon"
  - name: "ansible.platform"
  - name: "ansible.posix"
  - name: "ansible.utils"
  - name: "azure.azcollection"
  - name: "community.general"
  - name: "vmware.vmware"
  - name: "community.aws"
  - name: "containers.podman"
  - name: "redhat.rhel_idm"
  - name: "redhat.rhel_system_roles"
  - name: "redhat.satellite"
  - name: "redhat.satellite_operations"
  - name: "redhat.redhat_csp_download"
  - name: "ansible.hub"
