---
# These parameters are used for the post configuration of the ansible controller environment.


# AAP Manifest
redhat_manifest:
  name: "{{ ansible_fqdn }}"
  account: "{{ cdn_account_number_vault }}"
  cdn_username: "{{ cdn_username_vault }}"
  cdn_password: "{{ cdn_password_vault }}"
  content_access_mode: "org_environment"  # SCA mode
  path: "/tmp/aapcontroller.{{ _global_domain_name }}.zip"
  portal_url: "https://subscription.rhsm.redhat.com"
  state: present
  subs: "{{ satdev_subs_vault }}"
  validate_certs: false

# AAP Authentication
aap_ldap_domain_map: "dc=example,dc=ca"
aap_admin_username: "{{ aap_admin_username_vault }}"
aap_admin_password: "{{ aap_admin_password_vault }}"

aap_settings:
  - name: "authentication"
    settings:
      AUTH_LDAP_SERVER_URI: "ldap://{{ ipa_server_fqdn }}:389"
      AUTH_LDAP_BIND_DN: "{{ aap_auth_ldap_bind_dn_vault }}"
      AUTH_LDAP_BIND_PASSWORD: "{{ aap_auth_ldap_bind_password_vault }}"
      AUTH_LDAP_USER_DN_TEMPLATE: "uid=%(user)s,cn=users,cn=accounts,{{ aap_ldap_domain_map }}"
      AUTH_LDAP_GROUP_TYPE: "NestedMemberDNGroupType"
      AUTH_LDAP_REQUIRE_GROUP: "cn=aapgroup-user,cn=groups,cn=accounts,{{ aap_ldap_domain_map }}"
      AUTH_LDAP_GROUP_SEARCH: '["cn=groups,cn=accounts,{{ aap_ldap_domain_map }}","SCOPE_SUBTREE","(objectClass=posixGroup)"]'
      AUTH_LDAP_GROUP_TYPE_PARAMS:
        member_attr: "member"
        name_attr: "cn"
      AUTH_LDAP_USER_FLAGS_BY_GROUP: '{ "is_superuser": [ "cn=aapgroup-administrator,cn=groups,cn=accounts,{{ aap_ldap_domain_map }}"] }'
      AUTH_LDAP_USER_ATTR_MAP:
        email: "mail"
        first_name: "givenName"
        last_name: "sn"
