---

templates_soe_qa:
  - name: "QA1DeployQATestServers"
    description: "Deploy JBoss, LAMP and Wordpress test machines to Qualification"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "create_hosts.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      host_build_comment: "Created by rhis-builder"
      deploy: true
      post_deploy_timeout: 600  # seconds
      use_sync_build: false
      enable_debug_logging: false
      satellite_validate_certs: true
      platform_hosts:
        - fqdn: "qatestjboss2.{{ _global_domain_name }}"
          delete_host: false
          organization: "Default Organization"
          location: "Default Location"
          hostgroup: "hg_x86_64_rhel8_vm/qa/soe_jboss"
          kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
          compute_resource: "VMware_Lab"
          compute_profile: "2-Medium"
          mac: "00:50:56:ff:ff:ff"
        - fqdn: "qatestlamp2.{{ _global_domain_name }}"
          delete_host: false
          organization: "Default Organization"
          location: "Default Location"
          hostgroup: "hg_x86_64_rhel8_vm/qa/soe_lamp"
          kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
          compute_resource: "VMware_Lab"
          compute_profile: "2-Medium"
          mac: "00:50:56:ff:ff:ff"
        - fqdn: "qatestwordpress2.{{ _global_domain_name }}"
          delete_host: false
          organization: "Default Organization"
          location: "Default Location"
          hostgroup: "hg_x86_64_rhel8_vm/qa/soe_wordpress"
          kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
          compute_resource: "VMware_Lab"
          compute_profile: "2-Medium"
          mac: "00:50:56:ff:ff:ff"

  - name: "QA2SnapshotQATestServers"
    description: "Snapshot JBoss, LAMP and Wordpress test machines in Qualification"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_create_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "parmstrong.ca"
      datacenter_folder: "/parmstrong.ca/vm"
      vmware_validate_certs: true
      host_list:
        - name: qatestjboss2.{{ _global_domain_name }}
          snap_name: qatestjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: qatestlamp2.{{ _global_domain_name }}
          snap_name: qatestlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: qatestwordpress2.{{ _global_domain_name }}
          snap_name: qatestwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "QA3.1.1BuildQAJBoss"
    description: "QA Deploy JBoss application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_qa_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/jboss-standalone/main.yml"
    limit: "JBoss"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      jboss_deploy_standalone: true
      http_port: 8080
      https_port: 8443
      sample_app_git_repo: "https://github.com/parmstro/jboss-eap-quickstarts.git"
      sample_app_root: "/samples/jboss"
      sample_app_dir: "kitchensink/"
      app_fingerprint: "/samples/jboss/c0df90d8-5173-4e65-bc82-88b6033fc6a0"

  - name: "QA3.1.2TestQAJBoss"
    description: "QA Test JBoss application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_qa_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/jboss-standalone/deploymenttest.yml"
    limit: "JBoss"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      jboss_deploy_standalone: true
      http_port: 8080
      https_port: 8443
      sample_app_git_repo: "https://github.com/parmstro/jboss-eap-quickstarts.git"
      sample_app_root: "/samples/jboss"
      sample_app_dir: "kitchensink/"
      app_fingerprint: "/samples/jboss/c0df90d8-5173-4e65-bc82-88b6033fc6a0"

  - name: "QA3.2.1BuildQALAMP"
    description: "Build LAMP stack application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_qa_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/lamp_simple/main.yml"
    limit: "LAMP"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "QA3.2.2TestQALAMP"
    description: "QA Test LAMP stack application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_qa_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/lamp_simple/deploymenttest.yml"
    limit: "LAMP"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "QA3.3.1BuildQAWordpress"
    description: "QA Build WordPress application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_qa_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/wordpress-nginx/main.yml"
    limit: "WordPress"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "QA3.3.2TestQAWordpress"
    description: "QA Test WordPress application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_qa_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/wordpress-nginx/deploymenttest.yml"
    limit: "WordPress"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "QA4PromoteToProd"
    description: "Promote the SOE Content for JBoss, LAMP and Wordpress machines to Qualification"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "promote_only.yml"
    become_enabled: true
    credentials:
      - idm_machine
      - default_vault
    variables:
      force_promote_all: true
      description: "Published by rhis-builder"
      satellite_validate_certs: true
      source_lce: "SOE_Qualification"
      target_lce: "SOE_Production"
      content_views:
        - name: "SOE_RHEL8"
      composite_content_views:
        - name: "SOE_JBoss"
        - name: "SOE_RHEL8EPEL"

  - name: "QA5DeleteQASnapshots"
    description: "Delete QA test machine snapshots"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_delete_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "parmstrong.ca"
      datacenter_folder: "/parmstrong.ca/vm"
      vmware_validate_certs: true
      host_list:
        - name: qatestjboss2.{{ _global_domain_name }}
          snap_name: qatestjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: qatestlamp2.{{ _global_domain_name }}
          snap_name: qatestlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: qatestwordpress2.{{ _global_domain_name }}
          snap_name: qatestwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "QA6FPowerOffQATestServers"
    description: "PowerOff JBoss, LAMP and Wordpress test machines in Qualification"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_power_off_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "parmstrong.ca"
      datacenter_folder: "/parmstrong.ca/vm"
      vmware_validate_certs: true
      host_list:
        - name: qatestjboss2.{{ _global_domain_name }}
        - name: qatestlamp2.{{ _global_domain_name }}
        - name: qatestwordpress2.{{ _global_domain_name }}

  - name: "QA6SDeleteQATestServers"
    description: "After approval, delete JBoss, LAMP and Wordpress test machines in Qualification"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "delete_hosts.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      host_list:
        - name: qatestjboss2.{{ _global_domain_name }}
        - name: qatestlamp2.{{ _global_domain_name }}
        - name: qatestwordpress2.{{ _global_domain_name }}
