---

templates_vm_day_2:
  - name: "VMwareCreateSnapshot"
    description: "Snaphot JBoss, LAMP and Wordpress test machines to Development"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_create_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "VMwarePowerOffVM"
    description: "Power-off test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_power_off_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwarePowerOnVM"
    description: "Power-on test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_power_on_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareRebootGuestOS"
    description: "Reboot test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_reboot_guest_os.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareRemoveAllSnaps"
    description: "Remove all snapshots from test machines"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_remove_all_snapshots.yml"
    become_enabled: true
    credentials:
      - "default_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "VMwareRestartVM"
    description: "Restart the test machine vm"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_restart_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareRevertSnaps"
    description: "Revert the VM to a previous snapshot"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_revert_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "VMwareShutdownGuestOS"
    description: "Graceful shutdown of test machine vm"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_shutdown_guest_os.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}

  - name: "VMwareSuspendVM"
    description: "Suspend test machine vm - use with caution"
    job_type: "run"
    organization: "Default"
    inventory: "TheProvisioner"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_suspend_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "{{ _global_domain_name }}.ca"
      datacenter_folder: "/{{ _global_domain_name }}/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss.{{ _global_domain_name }}
        - name: testlamp.{{ _global_domain_name }}
        - name: testwordpress.{{ _global_domain_name }}
