---

- name: "Check if the host exists and is reachable"
  connection: local
  block:

    - name: "Assume the host does not exist"
      ansible.builtin.set_fact:
        host_exists: false

    - name: "Can we resolve the host?"
      ansible.builtin.assert:
        that: "{{ host.fqdn is ansible.utils.resolvable }}"

    - name: "Can we ssh to host?"
      ansible.builtin.wait_for:
        timeout: 60
        sleep: 10
        port: 22
        host: "{{ host.fqdn }}"
        search_regex: OpenSSH

    - name: "Is the host responsive?"
      ansible.builtin.command: "echo 'I am alive.'"
      delegate_to: "{{ host.fqdn }}"
      changed_when: true
      register: result

    - name: "The host exists"
      ansible.builtin.set_fact:
        host_exists: true
      when: result.stdout == "I am alive."

  rescue:

    - name: "The host does not exist"
      ansible.builtin.set_fact:
        host_exists: false
