---
# This role is applied to the provisioner node.
# The provisioner node is responsible for bootstrapping the remainder of the environment using Satellite
#

- name: "Create the ansible platform hosts"
  ansible.builtin.include_tasks: "create_host_from_hostgroup.yml"
  loop: "{{ platform_hosts }}"
  loop_control:
    loop_var: host
  register: async_list

# update logic to only monitor hosts being actively built

- name: "Will monitoring this list of hosts for completion"
  when:
    - hosts_to_monitor is defined
    - (hosts_to_monitor | length) > 0
  ansible.builtin.debug:
    var: hosts_to_monitor

- name: "Wait for all nodes to be built- Task will complete when the last host is up and running."
  when:
    - hosts_to_monitor is defined
    - (hosts_to_monitor | length) > 0
  ansible.builtin.wait_for:
    timeout: 7200
    sleep: 60
    port: 22
    host: "{{ host.fqdn }}"
    search_regex: "OpenSSH"
  loop: "{{ hosts_to_monitor }}"
  loop_control:
    loop_var: host
  become: false  # no root ssh login

- name: "Wait an additional time out for any post configuration."
  when:
    - hosts_to_monitor is defined
    - (hosts_to_monitor | length) > 0
  ansible.builtin.wait_for:
    timeout: "{{ post_deploy_timeout }}"
    sleep: 60
    port: 22
    host: "{{ host.fqdn }}"
    search_regex: "OpenSSH"
  loop: "{{ hosts_to_monitor }}"
  loop_control:
    loop_var: host
  become: false  # no root ssh login

- name: "Ensure built systems are patched to latest"
  when:
    - hosts_to_monitor is defined
    - (hosts_to_monitor | length) > 0
  redhat.satellite.job_invocation:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    use_gssapi: "{{ satellite_use_gssapi | default(omit) }}"
    server_url: "{{ satellite_url }}"
    job_template: "Update packages by search query - Katello Ansible Default"
    search_query: "name ^ ({{ host.fqdn }})"
    validate_certs: "{{ satellite_validate_certs }}"
  loop: "{{ hosts_to_monitor }}"
  loop_control:
    loop_var: host
