---

workflow_soe_content_delivery_pipeline_qa:
  name: "SOE_ContentDeliveryPipeline_QA"
  description: "SOE content delivery pipeline for the Development Lifecycle"
  organization: "Default"
  state: present
  workflow_nodes:
    - identifier: "DeployQA"
      unified_job_template:
        name: "QA1DeployQATestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "SnapshotQA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "SnapshotQA"
      unified_job_template:
        name: "QA2SnapshotQATestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "ConfigureApp1QA"
          - identifier: "ConfigureApp2QA"
          - identifier: "ConfigureApp3QA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "ConfigureApp1QA"
      unified_job_template:
        name: "QA3.1.1BuildQAJBoss"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "TestApp1QA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "TestApp1QA"
      unified_job_template:
        name: "QA3.1.2TestQAJBoss"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNextQA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "ConfigureApp2QA"
      unified_job_template:
        name: "QA3.2.1BuildQALAMP"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "TestApp2QA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "TestApp2QA"
      unified_job_template:
        name: "QA3.2.2TestQALAMP"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNextQA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "ConfigureApp3QA"
      unified_job_template:
        name: "QA3.3.1BuildQAWordpress"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "TestApp3QA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "TestApp3QA"
      unified_job_template:
        name: "QA3.3.2TestQAWordpress"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "PromoteNextQA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "PromoteNextQA"
      all_parents_must_converge: true
      unified_job_template:
        name: "QA4PromoteToProd"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "DeleteSnapshotQA"
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "DeleteSnapshotQA"
      unified_job_template:
        name: "QA5DeleteQASnapshots"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes:
          - identifier: "ApproveDeleteHostsQA"
        failure_nodes:
          - identifier: "PowerOffHostsQA"
        always_nodes: []
        credentials: []
    - identifier: "ApproveDeleteHostsQA"
      unified_job_template:
        name: "ApproveDeleteHostsQA"
        timeout: 10800
        type: workflow_approval
        description: "Approved to delete test hosts?"
      related:
        success_nodes:
          - identifier: "DeleteHostsQA"
        failure_nodes:
          - identifier: "PowerOffHostsQA"
        always_nodes: []
        credentials: []
    - identifier: "DeleteHostsQA"
      unified_job_template:
        name: "QA6SDeleteQATestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
    - identifier: "PowerOffHostsQA"
      organization: "Default"
      unified_job_template:
        name: "QA6FPowerOffQATestServers"
        organization:
          name: "Default"
        type: job_template
      related:
        success_nodes: []
        failure_nodes: []
        always_nodes: []
        credentials: []
