---

templates_soe_dev:
  - name: "Dev1PublishContent"
    description: "Publish the SOE Content for JBoss, LAMP and Wordpress"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "publish_only.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      force_publish_all: true
      skip_publish_all: false
      description: "Published by rhis-builder-pipelines"
      satellite_validate_certs: true
      content_views:
        - name: "EPEL8"
          date_filter_name: "ErrataByDate"
        - name: "JBossEAP74"
          date_filter_name: "ErrataByDate"
        - name: "SOE_RHEL8"
          date_filter_name: "ErrataByDate"
      composite_content_views:
        - name: "SOE_JBoss"
        - name: "SOE_RHEL8EPEL"

  - name: "Dev2PromoteToDev"
    description: "Promote the SOE Content for JBoss, LAMP and Wordpress to Development"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "promote_only.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      force_promote_all: true
      description: "Promoted by rhis-builder-pipelines"
      satellite_validate_certs: true
      source_lce: "Library"
      target_lce: "SOE_Development"
      content_views:
        - name: "SOE_RHEL8"
      composite_content_views:
        - name: "SOE_JBoss"
        - name: "SOE_RHEL8EPEL"

  - name: "Dev3DeployTestServers"
    description: "Deploy JBoss, LAMP and Wordpress test machines to Development"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "create_hosts.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      host_build_comment: "Created by ansible for content test"
      deploy: true
      post_deploy_timeout: 600  # seconds
      use_sync_build: false
      enable_debug_logging: false
      satellite_validate_certs: true
      platform_hosts:
        - fqdn: "testjboss2.{{ _global_domain_name }}"
          delete_host: false
          organization: "Default Organization"
          location: "Default Location"
          hostgroup: "hg_x86_64_rhel8_vm/dev/soe_jboss"
          kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
          compute_resource: "vcenter.{{ _global_domain_name }}"
          compute_profile: "2-Medium"
          mac: "00:50:56:ff:ff:ff"
        - fqdn: "testlamp2.{{ _global_domain_name }}"
          delete_host: false
          organization: "Default Organization"
          location: "Default Location"
          hostgroup: "hg_x86_64_rhel8_vm/dev/soe_lamp"
          kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
          compute_resource: "vcenter.{{ _global_domain_name }}"
          compute_profile: "2-Medium"
          mac: "00:50:56:ff:ff:ff"
        - fqdn: "testwordpress2.{{ _global_domain_name }}"
          delete_host: false
          organization: "Default Organization"
          location: "Default Location"
          hostgroup: "hg_x86_64_rhel8_vm/dev/soe_wordpress"
          kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
          compute_resource: "vcenter.{{ _global_domain_name }}"
          compute_profile: "2-Medium"
          mac: "00:50:56:ff:ff:ff"

  - name: "Dev4SnapshotTestServers"
    description: "Deploy JBoss, LAMP and Wordpress test machines to Development"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_create_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "parmstrong.ca"
      datacenter_folder: "/parmstrong.ca/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "Dev5.1.1BuildJBoss"
    description: "Deploy JBoss application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/jboss-standalone/main.yml"
    limit: "JBoss"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      jboss_deploy_standalone: true
      http_port: 8080
      https_port: 8443
      sample_app_git_repo: "https://github.com/parmstro/jboss-eap-quickstarts.git"
      sample_app_root: "/samples/jboss"
      sample_app_dir: "kitchensink/"
      app_fingerprint: "/samples/jboss/c0df90d8-5173-4e65-bc82-88b6033fc6a0"

  - name: "Dev5.1.2TestJBoss"
    description: "Test JBoss application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/jboss-standalone/deploymenttest.yml"
    limit: "JBoss"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      jboss_deploy_standalone: true
      http_port: 8080
      https_port: 8443
      sample_app_git_repo: "https://github.com/parmstro/jboss-eap-quickstarts.git"
      sample_app_root: "/samples/jboss"
      sample_app_dir: "kitchensink/"
      app_fingerprint: "/samples/jboss/c0df90d8-5173-4e65-bc82-88b6033fc6a0"

  - name: "Dev5.2.1BuildLAMP"
    description: "Build LAMP stack application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/lamp_simple/main.yml"
    limit: "LAMP"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "Dev5.2.2TestLAMP"
    description: "Test LAMP stack application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/lamp_simple/deploymenttest.yml"
    limit: "LAMP"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "Dev5.3.1BuildWordpress"
    description: "Build WordPress application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/wordpress-nginx/main.yml"
    limit: "WordPress"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "Dev5.3.2TestWordpress"
    description: "Test WordPress application"
    job_type: "run"
    organization: "Default"
    inventory: "SOE_pipeline_inventory"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "testcontent/wordpress-nginx/deploymenttest.yml"
    limit: "WordPress"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"

  - name: "Dev6PromoteToQA"
    description: "Promote the SOE Content for JBoss, LAMP and Wordpress machines to Qualification"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "promote_only.yml"
    become_enabled: true
    credentials:
      - idm_machine
      - default_vault
    variables:
      force_promote_all: true
      description: "Published by rhis-builder-pipelines"
      satellite_validate_certs: true
      source_lce: "SOE_Development"
      target_lce: "SOE_Qualification"
      content_views:
        - name: "SOE_RHEL8"
      composite_content_views:
        - name: "SOE_JBoss"
        - name: "SOE_RHEL8EPEL"

  - name: "Dev7DeleteSnapshots"
    description: "Delete test machine snapshots"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_delete_snapshot.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "parmstrong.ca"
      datacenter_folder: "/parmstrong.ca/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
          snap_name: testjboss2.original
          snap_description: "test base jboss build - delete me"
          quiesce: true
        - name: testlamp2.{{ _global_domain_name }}
          snap_name: testlamp2.original
          snap_description: "test base LAMP build - delete me"
          quiesce: true
        - name: testwordpress2.{{ _global_domain_name }}
          snap_name: testwordpress2.original
          snap_description: "test base WordPress build - delete me"
          quiesce: true

  - name: "Dev8FPowerOffTestServers"
    description: "PowerOff JBoss, LAMP and Wordpress test machines in Dev"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "vmware/vmw_power_off_vm.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      vault_path: "vars/vault.yml"
      vars_path: "vars/main.yml"
      vcenter_hostname: "vcenter.{{ _global_domain_name }}"
      datacenter_name: "parmstrong.ca"
      datacenter_folder: "/parmstrong.ca/vm"
      vmware_validate_certs: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
        - name: testlamp2.{{ _global_domain_name }}
        - name: testwordpress2.{{ _global_domain_name }}

  - name: "Dev8SDeleteTestServers"
    description: "After approval, delete JBoss, LAMP and Wordpress test machines in Dev"
    job_type: "run"
    organization: "Default"
    inventory: "TheAutomationController"
    project: "rhis-builder-pipelines"
    execution_environment: "satellite_ee"
    playbook: "delete_hosts.yml"
    become_enabled: true
    credentials:
      - "idm_machine"
      - "default_vault"
    variables:
      enable_debug_logging: true
      host_list:
        - name: testjboss2.{{ _global_domain_name }}
        - name: testlamp2.{{ _global_domain_name }}
        - name: testwordpress2.{{ _global_domain_name }}
