---

aap_settings:
  - name: "authentication"
    settings:
      AUTH_LDAP_SERVER_URI: "ldap://{{ ipa_server_fqdn }}:389"
      AUTH_LDAP_BIND_DN: "{{ aap_auth_ldap_bind_dn_vault }}"
      AUTH_LDAP_BIND_PASSWORD: "{{ aap_auth_ldap_bind_password_vault }}"
      AUTH_LDAP_USER_DN_TEMPLATE: "uid=%(user)s,cn=users,cn=accounts,{{ aap_ldap_domain_map }}"
      AUTH_LDAP_GROUP_TYPE: "NestedMemberDNGroupType"
      AUTH_LDAP_REQUIRE_GROUP: "cn=aapgroup-user,cn=groups,cn=accounts,{{ aap_ldap_domain_map }}"
      AUTH_LDAP_GROUP_SEARCH: '["cn=groups,cn=accounts,{{ aap_ldap_domain_map }}","SCOPE_SUBTREE","(objectClass=posixGroup)"]'
      AUTH_LDAP_GROUP_TYPE_PARAMS:
        member_attr: "member"
        name_attr: "cn"
      AUTH_LDAP_USER_FLAGS_BY_GROUP: '{ "is_superuser": [ "cn=aapgroup-administrator,cn=groups,cn=accounts,{{ aap_ldap_domain_map }}"] }'
      AUTH_LDAP_USER_ATTR_MAP:
        email: "mail"
        first_name: "givenName"
        last_name: "surname"
