---

# Manage the redhat_manifest states
- name: "Ensure the manifest state"
  ansible.builtin.include_tasks: "set_manifest_state.yml"

- name: "Ensure the proper subscriptions are attached"
  when: "redhat_manifest.state == 'present'"
  ansible.builtin.include_tasks: "subs_2_manifest.yml"
  loop: "{{ redhat_manifest.subs }}"
  loop_control:
    loop_var: sub
  no_log: true

- name: "Fetch the manifest"
  when: "redhat_manifest.state == 'present'"
  ansible.builtin.include_tasks: "fetch_manifest.yml"
