---
# add a list of credentials to aap

- name: "Add the list of credentials to the Controller"
  when: aap_credentials is defined and (aap_credentials | length) > 0
  ansible.builtin.include_tasks: "ensure_aap_credential.yml"
  loop: "{{ aap_credentials }}"
  loop_control:
    loop_var: aap_credential
  no_log: true
