---

# This tasks creates the projects
- name: "Refresh the Anisble Automation Hub offline token" # noqa: command-instead-of-shell
  ansible.builtin.shell: "{{ redhat_automation_hub_token_refresh_cmd }}"
  register: token_refresh_result
  changed_when: token_refresh_result.rc == 0

- name: "Add the projects to the controller"
  when: aap_projects is defined and (aap_projects | length) > 0
  ansible.builtin.include_tasks: "ensure_aap_project.yml"
  loop: "{{ aap_projects }}"
  loop_control:
    loop_var: aap_project
  no_log: true
