---
# This tasks goes through the list of templates

- name: "Process the list of job template lists"
  when: aap_job_templates_list is defined and (aap_job_templates_list | length) > 0
  ansible.builtin.include_tasks: "add_aap_templates.yml"
  loop: "{{ aap_job_templates_list }}"
  loop_control:
    loop_var: aap_job_templates
  no_log: true
