---
# Add execution_environment to controller

- name: "Ensure the EEs are registered on the controller"
  ansible.controller.execution_environment:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    validate_certs: "{{ aap_validate_certs }}"
    name: "{{ execution_environment.name }}"
    image: "{{ execution_environment.image }}"
    pull: "{{ execution_environment.pull | default(omit) }}"
    organization: "{{ execution_environment.organization | default(omit) }}"
    description: "{{ execution_environment.description | default(omit) }}"
    credential: "{{ execution_environment.credential | default(omit) }}"

...
