---
# Add execution_environment to controller

- name: "Ensure the EEs are registered on the controller"
  ansible.controller.execution_environment:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    name: "{{ aap_execution_environment.name }}"
    image: "{{ aap_execution_environment.image }}"
    pull: "{{ aap_execution_environment.pull | default(omit) }}"
    organization: "{{ aap_execution_environment.organization | default(omit) }}"
    description: "{{ aap_execution_environment.description | default(omit) }}"
    credential: "{{ aap_execution_environment.credential | default(omit) }}"
