---
# add a list of credentials to aap

- name: "Add the list of credentials to the Controller"
  when: aap_credential_types is defined and (aap_credential_types | length) > 0
  ansible.builtin.include_tasks: "ensure_aap_credential_type.yml"
  loop: "{{ aap_credential_types }}"
  loop_control:
    loop_var: aap_credential_type
  no_log: true

...
