---
# Ensure the workflow exists and then add the nodes

- name: "Ensure that workflow {{ aap_workflow_template.name }} is {{ aap_workflow_template.state }}" # noqa: name[template]
  ansible.controller.workflow_job_template:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    allow_simultaneous: "{{ aap_workflow_template.allow_simultaneous | default(omit) }}"
    ask_inventory_on_launch: "{{ aap_workflow_template.ask_inventory_on_launch | default(omit) }}"
    ask_labels_on_launch: "{{ aap_workflow_template.ask_labels_on_launch | default(omit) }}"
    ask_limit_on_launch: "{{ aap_workflow_template.ask_limits_on_launch | default(omit) }}"
    ask_scm_branch_on_launch: "{{ aap_workflow_template.ask_scm_branch_on_launch | default(omit) }}"
    ask_skip_tags_on_launch: "{{ aap_workflow_template.ask_skip_tags_on_launch | default(omit) }}"
    ask_tags_on_launch: "{{ aap_workflow_template.ask_tags_on_launch | default(omit) }}"
    ask_variables_on_launch: "{{ aap_workflow_template.ask_variables_on_launch | default(omit) }}"
    description: "{{ aap_workflow_template.description | default(omit) }}"
    destroy_current_nodes: "{{ aap_workflow_template.destroy_current_nodes | default(omit) }}"
    extra_vars: "{{ aap_workflow_template.extra_vars | default(omit) }}"
    inventory: "{{ aap_workflow_template.inventory | default(omit) }}"
    job_tags: "{{ aap_workflow_template.job_tags | default(omit) }}"
    labels: "{{ aap_workflow_template.labels | default(omit) }}"
    limit: "{{ aap_workflow_template.limit | default(omit) }}"
    name: "{{ aap_workflow_template.name }}"
    new_name: "{{ aap_workflow_template.new_name | default(omit) }}"
    organization: "{{ aap_workflow_template.organization | default('Default') }}"
    scm_branch: "{{ aap_workflow_template.scm_branch | default(omit) }}"
    skip_tags: "{{ aap_workflow_template.skip_tags | default(omit) }}"
    state: "{{ aap_workflow_template.state }}"
    survey_enabled: "{{ aap_workflow_template.survey_enabled | default(omit) }}"
    survey_spec: "{{ aap_workflow_template.survey_spec | default(omit) }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    webhook_credential: "{{ aap_workflow_template.webhook_credential | default(omit) }}"
    webhook_service: "{{ aap_workflow_template.webhook_service | default(omit) }}"
    workflow_nodes: "{{ aap_workflow_template.workflow_nodes | default(omit) }}"

# There appears to be a bug in workflow_job_template_nodes
# 'NoneType' object is not subscriptable at line 107 (366 in the file)

# - name: "Add the workflow nodes to the workflow"
#   ansible.builtin.include_tasks: "ensure_aap_workflow_node.yml"
#   loop: "{{ workflow.workflow_nodes | reverse }}"
#   loop_control:
#     loop_var: workflow_node
