---
# This task ensures an aap_inventory status

- name: "Ensure the inventory {{ aap_inventory.name }} is {{ aap_inventory.state }}" # noqa name[template]
  ansible.controller.inventory:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    description: "{{ aap_inventory.description | default(omit) }}"
    host_filter: "{{ aap_inventory.host_filter | default(omit) }}"
    input_inventories: "{{ aap_inventory.input_inventories | default(omit) }}"
    instance_groups: "{{ aap_inventory.instance_groups | default(omit) }}"
    kind: "{{ aap_inventory.kind | default(omit) }}"
    name: "{{ aap_inventory.name }}"
    new_name: "{{ aap_inventory.new_name | default(omit) }}"
    organization: "{{ aap_inventory.organization | default('Default') }}"
    state: "{{ aap_inventory.state | default(present) }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"
    variables: "{{ aap_inventory.variables | default(omit) }}"

...
