---
# Add the galaxy or hub credential to the organization

- name: "Add the credential to the organization"
  ansible.controller.organization:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    name: "{{ org.name }}"
    galaxy_credentials: "{{ org.galaxy_credentials }}"
    validate_certs: "{{ aap_validate_certs }}"
