---

# This adds a credential type to the aap controller configuration

- name: "Add the credential type {{ aap_credential_type.name }}"
  ansible.controller.credential_type:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    name: "{{ aap_credential_type.name }}"
    new_name: "{{ aap_credential_type.name | default(omit) }}"
    description: "{{ aap_credential_type.description | default(omit) }}"
    kind: "{{ aap_credential_type.kind | default('cloud') }}"
    inputs: "{{ aap_credential_type.inputs }}"
    injectors: "{{ aap_credential_type.injectors }}"
    request_timeout: "{{ aap_credential_type.request_timeout | default(omit) }}"
    state: "{{ aap_credential_type.state | default(omit) }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}

...
