---
# This task ensures an inventory source status

- name: "Ensure the inventory state {{ aap_inventory_source.name }}"
  ansible.controller.inventory_source:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    credential: "{{ aap_inventory_source.credential }}"
    description: "{{ aap_inventory_source.description | default(omit) }}"
    enabled_value: "{{ aap_inventory_source.enabled_value | default(omit) }}"  # e.g. powered_on
    enabled_var: "{{ aap_inventory_source.enabled_var | default(omit) }}"      # e.g. status.power_state
    execution_environment: "{{ aap_inventory_source.execution_environment | default('Default') }}"
    host_filter: "{{ aap_inventory_source.host_filter | default(omit) }}"
    inventory: "{{ aap_inventory_source.inventory }}"
    limit: "{{ aap_inventory_source.limit | default(omit) }}"
    name: "{{ aap_inventory_source.name }}"
    new_name: "{{ aap_inventory_source.new_name | default(omit) }}"
    organization: "{{ aap_inventory.organization | default('Default') }}"
    overwrite: "{{ aap_inventory_source.overwrite | default(omit) }}"
    overwrite_vars: "{{ aap_inventory_source.overwrite_vars | default(omit) }}"
    source: "{{ aap_inventory_source.source }}"
    state: "{{ aap_inventory_source.state | default(present) }}"
    update_on_launch: "{{ aap_inventory_source.update_on_launch | default(omit) }}"
    validate_certs: "{{ aap_validate_certs }}"

...
