---

- name: "Ensure that organization {{ aap_organization.name }} is {{ aap_organization.state }}"  # noqa name[template]
  ansible.controller.organization:
    controller_host: "{{ aap_platform_host }}"
    controller_username: "{{ aap_platform_username }}"
    controller_password: "{{ aap_platform_password }}"
    controller_config_file: "{{ aap_controller_config_file | default(omit) }}"
    controller_oauthtoken: "{{ aap_controller_oauthtoken | default(omit) }}"
    custom_virtualenv: "{{ aap_organization.custom_virtualenv | default(omit) }}"
    default_environment: "{{ aap_organization.default_environment | default(omit) }}"
    description: "{{ aap_organization.description | default(omit) }}"
    galaxy_credentials: "{{ aap_organization.galaxy_credentials | default(omit) }}"
    instance_groups: "{{ aap_organization.instance_groups | default(omit) }}"
    max_hosts: "{{ aap_organization.max_hosts | default(omit) }}"
    name: "{{ aap_organization.name }}"
    new_name: "{{ aap_organization.new_name | default(omit) }}"
    notification_templates_approvals: "{{ aap_organization.notification_templates_approvals | default(omit) }}"
    notification_templates_error: "{{ aap_organization.notification_templates_error | default(omit) }}"
    notification_templates_started: "{{ aap_organization.notification_templates_started | default(omit) }}"
    notification_templates_success: "{{ aap_organization.notification_templates_success | default(omit) }}"
    request_timeout: "{{ aap_organization.request_timeout | default(omit) }}"
    state: "{{ aap_organization.state | default(present) }}"
    validate_certs: "{{ aap_validate_certs | default(true) }}"

...
